inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Gemfile
    - Guardfile
    - Rakefile
    - bin/searchlink
    - lib/**/*.rb
  Exclude:
    - 'searchlink.rb'
    - pkg/**/*.rb

require:
  - rubocop-rspec
  - rubocop-rake

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - bin/howzit
    - lib/*.rb

Style/RegexpLiteral:
  Exclude:
    - Guardfile
